name: Run Spotify Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      WIND_USERNAME: ${{ secrets.WIND_USERNAME }}
      WIND_PASSWORD: ${{ secrets.WIND_PASSWORD }}
      SPOTIFY_CLIENT_ID_1: ${{ secrets.SPOTIFY_CLIENT_ID_1 }}
      SPOTIFY_CLIENT_SECRET_1: ${{ secrets.SPOTIFY_CLIENT_SECRET_1 }}
      SPOTIFY_CLIENT_ID_2: ${{ secrets.SPOTIFY_CLIENT_ID_2 }}
      SPOTIFY_CLIENT_SECRET_2: ${{ secrets.SPOTIFY_CLIENT_SECRET_2 }}
      SPOTIFY_CLIENT_ID_3: ${{ secrets.SPOTIFY_CLIENT_ID_3 }}
      SPOTIFY_CLIENT_SECRET_3: ${{ secrets.SPOTIFY_CLIENT_SECRET_3 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Windscribe VPN CLI
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:windscribe/release -y
          sudo apt-get update
          sudo apt-get install -y windscribe-cli

      - name: Connect to Windscribe VPN
        run: |
          windscribe login --username "$sumannaidur" --password "$M)$pB#+D/3/n&+8"
          windscribe connect best

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        run: python main.py
